dict_type_variables = {
    "name": {"Type": "Textuelle", "File": "Agents.csv","Log":False, "Seuil": 5},
    "siret": {"Type": "Textuelle", "File": "Agents.csv","Log":False},
    "address": {"Type": "Textuelle", "File": "Agents.csv","Log":False, "Seuil": 70},
    "city": {"Type": "Textuelle", "File": "Agents.csv","Log":False, "Seuil": 1000},
    "zipcode": {"Type": "Textuelle", "File": "Agents.csv","Log":False},
    "country": {"Type": "Textuelle", "File": "Agents.csv","Log":False, "Seuil": 5000},
    "department": {"Type": "Textuelle", "File": "Agents.csv","Log":False, "Seuil": 2000},
    "longitude": {"Type": "Numérique", "File": "Agents.csv","Log":True},
    "latitude": {"Type": "Numérique", "File": "Agents.csv","Log":True},
    "weight": {"Type": "Numérique", "File": "Criteria.csv","Log":True},
    "type": {"Type": "Categorielle", "File": "Criteria.csv","Log":False},
    "correctionsNb": {"Type": "Numérique", "File": "Lots.csv","Log":True},
    "cancelled": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "awardDate": {"Type": "Textuelle", "File": "Lots.csv","Log":False},
    "awardEstimatedPrice": {"Type": "Numérique", "File": "Lots.csv","Log":True},
    "awardPrice": {"Type": "Numérique", "File": "Lots.csv","Log":True},
    "cpv": {"Type": "Textuelle", "File": "Lots.csv","Log":False},
    "tenderNumber": {"Type": "Numérique", "File": "Lots.csv","Log":True},
    "onBehalf": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "jointProcurement": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "fraAgreement": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "fraEstimated": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "numberTenders": {"Type": "Numérique", "File": "Lots.csv","Log":True},
    "accelerated": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "outOfDirectives": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "contractorSme": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "numberTendersSme": {"Type": "Numérique", "File": "Lots.csv","Log":True},
    "subContracted": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "gpa": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "multipleCae": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "typeOfContract": {"Type": "Textuelle", "File": "Lots.csv","Log":False},
    "topType": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "renewal": {"Type": "Categorielle", "File": "Lots.csv","Log":False},
    "contractDuration": {"Type": "Numérique", "File": "Lots.csv","Log":True},
    "publicityDuration": {"Type": "Numérique", "File": "Lots.csv","Log":True},
}


dict_fichier_variables = {
    "name": "Agents.csv",
    "siret": "Agents.csv",
    "address": "Agents.csv",
    "city": "Agents.csv",
    "zipcode": "Agents.csv",
    "country": "Agents.csv",
    "department": "Agents.csv",
    "longitude": "Agents.csv",
    "latitude": "Agents.csv",
    "weight": "Criteria.csv",
    "type": "Criteria.csv",
    "correctionsNb": "Lots.csv",
    "cancelled": "Lots.csv",
    "awardDate": "Lots.csv",
    "awardEstimatedPrice": "Lots.csv",
    "awardPrice": "Lots.csv",
    "cpv": "Lots.csv",
    "tenderNumber": "Lots.csv",
    "onBehalf": "Lots.csv",
    "jointProcurement": "Lots.csv",
    "fraAgreement": "Lots.csv",
    "fraEstimated": "Lots.csv",
    "numberTenders": "Lots.csv",
    "accelerated": "Lots.csv",
    "outOfDirectives": "Lots.csv",
    "contractorSme": "Lots.csv",
    "numberTendersSme": "Lots.csv",
    "subContracted": "Lots.csv",
    "gpa": "Lots.csv",
    "multipleCae": "Lots.csv",
    "typeOfContract": "Lots.csv",
    "topType": "Lots.csv",
    "renewal": "Lots.csv",
    "contractDuration": "Lots.csv",
    "publicityDuration": "Lots.csv",
}
